# version: "3.9"

# services:
#   frontend:
#     container_name: sanctuary
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       - SANCTUARY_API_URL=http://host.docker.internal:3000/api
#       - NODE_ENV=production
#     networks:
#       - app-network

# networks:
#   app-network:

version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    # network_mode: "host"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: sanctuary
      POSTGRES_DB: sanctuary
    ports:
      - '5434:5432'
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/init.sql

  sanctuary:
    build: .
    container_name: front-end
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://sanctuary:password@localhost:5434/sanctuary
      - SANCTUARY_API_URL=http://host.docker.internal:3000/api
    ports:
    - "3000:3000"
    # network_mode: "host"
    depends_on:
      - postgres
    networks:
      - app-network

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - sanctuary

volumes:
  postgres:

networks:
  app-network: